GROUPING_RULES = {
    "Background": "Background",
    "__unused__": "Others",
    "Other_tissue": "Others",
    "Cartilage_costal": "Bones_and_cartilage",
    "Humerus_left": "Bones_and_cartilage",
    "Scapula_left": "Bones_and_cartilage",
    "Scapula_right": "Bones_and_cartilage",
    "Clavicle_left": "Bones_and_cartilage",
    "Clavicle_right": "Bones_and_cartilage",
    "Pelvis_right": "Bones_and_cartilage",
    "Sternum": "Bones_and_cartilage",
    "Cartilage_costal": "Bones_and_cartilage",
    "Intervertebral_disc": "Bones_and_cartilage",
    "Vertebrae_body": "Bones_and_cartilage",
    "Vertebrae_posterior_processes": "Bones_and_cartilage",
    "Spinal_canal": "Bones_and_cartilage",
    "Kidney_right": "Kidneys",
    "Kidney_left":  "Kidneys",
    "Adrenal_gland_right": "Kidneys",
    "Adrenal_gland_left": "Kidneys",
    "Lung": "Lungs",
    "Vein_pulmonary": "Blood_vessels",
    "Artery_brachiocephalic": "Blood_vessels",
    "Artery_subclavian_right": "Blood_vessels",
    "Artery_subclavian_left": "Blood_vessels",
    "Artery_common_carotid_right": "Blood_vessels",
    "Artery_common_carotid_left": "Blood_vessels",
    "Vein_brachiocephalic_left": "Blood_vessels",
    "Vein_brachiocephalic_right": "Blood_vessels",
    "Vena_cava_superior": "Blood_vessels",
    "Vena_cava_inferior": "Blood_vessels",
    "Vein_portal_and_splenic": "Blood_vessels",
    "Stomach_wall": "Stomach",
    "Stomach_lumen": "Stomach",
    "Esophagus_lumen": "Esophagus_and_trachea",
    "Esophagus_wall": "Esophagus_and_trachea",
    "Trachea_wall": "Esophagus_and_trachea",
    "Trachea_lumen": "Esophagus_and_trachea",
    "Thyroid_gland": "Esophagus_and_trachea",
    "Intestine_lumen": "Intestine",
    "Small_intestine_duodenum": "Intestine",
    "Intestine_wall": "Intestine",
    "Gallbladder_wall": "Gallbladder",
    "Gallbladder_bile": "Gallbladder",
    "Fat": "Fat",
    "SAT": "Fat",
    "Muscle": "Muscle",
    "Skin": "Skin",
    "Spleen": "Spleen",
    "Pancreas": "Pancreas",
    "Heart": "Heart_generic",
    "Atrial_appendage_left": "Heart_generic",
    "Liver": "Liver",
    "Aorta": "Aorta",
    "Spleen": "Spleen",
    "Spinal_cord": "Spinal_cord",
}

new_labels = set()
for value in GROUPING_RULES.values():
    new_labels.add(value)

foreground_labels = ["LV_Myocardium", "LV_blood_pool", "RV_blood_pool_myocardium"]
new_labels = new_labels.union(set(foreground_labels))

NEW_LABELS = sorted(list(new_labels))
